# NumPy

Read the link https://numpy.org/doc/stable/user/quickstart.html before starting the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2]:
A = np.arange(1, 16).reshape(3,5)

In [3]:
print("Number of dimensions (axes):", A.ndim)
print("Shape:", A.shape)
print("Size (total number of elements):", A.size)
print("Data type:", A.dtype)

Number of dimensions (axes): 2
Shape: (3, 5)
Size (total number of elements): 15
Data type: int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [4]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [5]:
subtraction = B - C
print("\nElementwise Subtraction (B - C):")
print(subtraction)

elementwise_mul = B * C
print("\nElementwise Multiplication (B * C):")
print(elementwise_mul)

matrix_mul = B @ C
print("\nMatrix Multiplication (B @ C):")
print(matrix_mul)


Elementwise Subtraction (B - C):
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

Elementwise Multiplication (B * C):
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matrix Multiplication (B @ C):
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on matrix D:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [6]:
D = np.arange(1, 10).reshape(3, 3)
print(D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
exp_D = np.exp(D)
print("\nElementwise Exponentiation (np.exp(D)):")
print(exp_D)

min_value = np.min(D)
print("\nMinimum value in the whole matrix:", min_value)

min_row = np.min(D, axis=1)
print("\nMinimum value in each row:", min_row)

min_col = np.min(D, axis=0)
print("\nMinimum value in each column:", min_col)

min_index = np.argmin(D)
print("\nIndex of minimum value in the whole matrix:", min_index)

min_index_row = np.argmin(D, axis=1)
print("\nIndex of minimum value in each row:", min_index_row)

sum_all = np.sum(D)
print("\nSum of all elements:", sum_all)

mean_col = np.mean(D, axis=0)
print("\nMean for each column:", mean_col)

median_col = np.median(D, axis=0)
print("\nMedian for each column:", median_col)


Elementwise Exponentiation (np.exp(D)):
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minimum value in the whole matrix: 1

Minimum value in each row: [1 4 7]

Minimum value in each column: [1 2 3]

Index of minimum value in the whole matrix: 0

Index of minimum value in each row: [0 0 0]

Sum of all elements: 45

Mean for each column: [4. 5. 6.]

Median for each column: [4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [8]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [9]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [10]:
NumPy returns a sub-array by dropping the extra axes.

SyntaxError: invalid syntax (3782058351.py, line 1)

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [ ]:
A

In [ ]:
for i in A:
    print(i)

In [ ]:
for element in A.flat:
    print(element)

### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [ ]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

In [ ]:
Creates a as 1D array of 30 elements
Reshapes a into b 3D array with three axes4
Prints a
Prints empty line
Prints b

Axis 0: 2 blocks
Axis 1: 3 rows per block
Axis 2: 5 elements per row

### Broadcasting
Read the link https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting and the document *"matematik_yh_kap_10"* (solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh) before starting the exercises below.  

If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Explain what the code below does. More specifically, b has three axes - what does this mean? 

##### Remark on Broadcasting when doing Linear Algebra calculations in Python. 
From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices.

In [ ]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [ ]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

In [ ]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

### Vector and matrix algebra

Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.

Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).

In [ ]:
import numpy as np

def add_mult_matrices(mat1, mat2, operation):
    if not isinstance(mat1, np.ndarray) or not isinstance(mat2, np.ndarray):
        raise TypeError("Both inputs must be NumPy arrays (np.ndarray).")
    
    if operation not in ['add', 'multiply']:
        raise ValueError("Operation must be either 'add' or 'multiply'.")
    
    if operation == 'add':
        if mat1.shape != mat2.shape:
            raise ValueError("For addition, both matrices must have the same shape.")
        return mat1 + mat2    
    elif operation == 'multiply':
        if mat1.shape[1] != mat2.shape[0]:
            raise ValueError(
                "For multiplication, number of columns in the first matrix must equal number of rows in the second matrix."
            )
        return mat1 @ mat2


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. Note, the function you created above can be used. 

In [11]:
import numpy as np

# Define vectors
x = np.array([4, 3])
v = np.array([3, 7, 0, 11])
v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])

# Uppgift 10.1.1
print("Uppgift 10.1.1")
print("Dimension of x:", x.shape[0])
print("5x =", 5 * x)
print("3x =", 3 * x)
print("5x + 3x =", 5 * x + 3 * x)
print("8x =", 8 * x)
print("4x - x =", 4 * x - x)
print("x^T =", x.reshape(1, -1))
print("||x|| =", np.linalg.norm(x))

# Uppgift 10.1.2
print("\nUppgift 10.1.2")
print("Dimension of v:", v.shape[0])
print("2v =", 2 * v)

# Uppgift 10.1.3
print("\nUppgift 10.1.3")
print("||v1|| =", np.linalg.norm(v1))
print("||v1 - v2|| =", np.linalg.norm(v1 - v2))


Uppgift 10.1.1
Dimension of x: 2
5x = [20 15]
3x = [12  9]
5x + 3x = [32 24]
8x = [32 24]
4x - x = [12  9]
x^T = [[4 3]]
||x|| = 5.0

Uppgift 10.1.2
Dimension of v: 4
2v = [ 6 14  0 22]

Uppgift 10.1.3
||v1|| = 7.14142842854285
||v1 - v2|| = 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

In [20]:
import numpy as np

# 10.2.1

A = np.array([[2, 1, -1],
              [1, -1, 1]])

B = np.array([[4, -2, 1],
              [2, -4, -2]])

C = np.array([[1, 2],
              [2, 1]])

D = np.array([[3, 4],
              [4, 3]])

E = np.array([[1],
              [2]])

I = np.array([[1, 0],
              [0, 1]])

print("Uppgift 10.2.1")

print("(a) 2A =\n", 2 * A)
print("\n(b) B - 2A =\n", B - 2 * A)

print("\n(c) 3C - 2E = NOT DEFINED (dimension mismatch)")

print("\n(d) 2D - 3C =\n", 2 * D - 3 * C)
print("\n(e) D^T + 2D =\n", D.T + 2 * D)
print("\n(f) 2C^T - 2D^T =\n", 2 * C.T - 2 * D.T)
print("\n(g) A^T - B = NOT DEFINED (dimension mismatch)")
print("\n(h) AC = NOT DEFINED (dimension mismatch)")
print("\n(i) CD =\n", C @ D)

print("\n(j) CB = NOT DEFINED (dimension mismatch)")
print("\n(k) CI =\n", C @ I)
print("\n(l) AB^T =\n", A @ B.T)


# 10.2.2

A_1022 = np.array([[2, 3, 4],
                   [5, 4, 1]])

print("\nUppgift 10.2.2")
print("A A^T =\n", A_1022 @ A_1022.T)


# 10.2.3

A_1023 = np.array([[1, 2],
                   [2, 4]])

B_1023 = np.array([[2, 1],
                   [1, 3]])

C_1023 = np.array([[4, 3],
                   [0, 2]])

print("\nUppgift 10.2.3")
print("AB =\n", A_1023 @ B_1023)
print("AC =\n", A_1023 @ C_1023)

print("\nCheck: AB == AC ?", np.array_equal(A_1023 @ B_1023, A_1023 @ C_1023))
print("Check: B == C ?", np.array_equal(B_1023, C_1023))


Uppgift 10.2.1
(a) 2A =
 [[ 4  2 -2]
 [ 2 -2  2]]

(b) B - 2A =
 [[ 0 -4  3]
 [ 0 -2 -4]]

(c) 3C - 2E = NOT DEFINED (dimension mismatch)

(d) 2D - 3C =
 [[3 2]
 [2 3]]

(e) D^T + 2D =
 [[ 9 12]
 [12  9]]

(f) 2C^T - 2D^T =
 [[-4 -4]
 [-4 -4]]

(g) A^T - B = NOT DEFINED (dimension mismatch)

(h) AC = NOT DEFINED (dimension mismatch)

(i) CD =
 [[11 10]
 [10 11]]

(j) CB = NOT DEFINED (dimension mismatch)

(k) CI =
 [[1 2]
 [2 1]]

(l) AB^T =
 [[5 2]
 [7 4]]

Uppgift 10.2.2
A A^T =
 [[29 26]
 [26 42]]

Uppgift 10.2.3
AB =
 [[ 4  7]
 [ 8 14]]
AC =
 [[ 4  7]
 [ 8 14]]

Check: AB == AC ? True
Check: B == C ? False


### Copies and Views
Read the link https://numpy.org/doc/stable/user/basics.copies.html before starting the exercises below. 

Basic indexing creates a view. How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?

In [21]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [22]:
print(v2.base is v1)

# if tru, v2 is a view of v1

True


In [23]:
yes, it will be changed as v2 is a view of v1

SyntaxError: invalid syntax (3787607604.py, line 1)